class_name MeshFactory
extends RefCounted
## Builds unit and structure models from the .amdl files in res://models/.
## They are generated by tools/models/build_models.py, from the STL sources in
## tools/models/stl/ or from procedural Tiberian Sun-style designs.
##
## Every model faces +Z. Metadata on the returned root:
##   "turret"        Node3D that rotates to aim
##   "muzzle_height" float
##   "walker"/"legs" walker leg animation ("leg_swing" = amplitude in radians)
##   "cutter"/"bin"  harvester parts
##
## Each triangle belongs to a material slot. Slots map to faction materials
## (palette) or to the owner's team colour, so models recolour like TS remaps.
## "<model>_<faction>.amdl" is used when it exists (Veil variants of buildings).

const MODEL_DIR := "res://models/"

static var _mats := {}
static var _models := {}
static var _grime: Texture2D


static func mat(color: Color, emissive := 0.0, rough := 0.65, metal := 0.25, grime := true) -> StandardMaterial3D:
	var key := "%s|%.2f|%.2f|%.2f|%s" % [color.to_html(), emissive, rough, metal, grime]
	if _mats.has(key):
		return _mats[key]
	var m := StandardMaterial3D.new()
	m.albedo_color = color
	m.roughness = rough
	m.metallic = metal
	m.vertex_color_use_as_albedo = true  # baked ambient occlusion
	if grime:
		# weathered, noisy panels like TS voxel shading
		m.albedo_texture = _grime_texture()
		m.uv1_triplanar = true
		m.uv1_world_triplanar = false
		m.uv1_scale = Vector3(2.5, 2.5, 2.5)
	if emissive > 0.0:
		m.albedo_color = color.darkened(0.55)  # keep the hue instead of blowing out to white
		m.emission_enabled = true
		m.emission = color
		m.emission_energy_multiplier = emissive
	_mats[key] = m
	return m


static func _grime_texture() -> Texture2D:
	if _grime:
		return _grime
	var img := Image.create(128, 128, false, Image.FORMAT_RGB8)
	var n := FastNoiseLite.new()
	n.seed = 1995
	n.frequency = 0.09
	n.fractal_octaves = 3
	var n2 := FastNoiseLite.new()
	n2.seed = 7
	n2.noise_type = FastNoiseLite.TYPE_VALUE
	n2.frequency = 0.6
	for y in 128:
		for x in 128:
			# tileable blotches plus fine speckle
			var v := n.get_noise_2d(x, y) * 0.5 + 0.5
			var s := n2.get_noise_2d(x, y) * 0.5 + 0.5
			var g := clampf(0.8 + 0.14 * v + 0.08 * (s - 0.5), 0.0, 1.0)
			img.set_pixel(x, y, Color(g, g, g * 0.98))
	img.generate_mipmaps()
	_grime = ImageTexture.create_from_image(img)
	return _grime


## Faction palette (design doc 6.1). Bastion: GDI-style khaki grey with gold
## trim. Veil: Nod-style gunmetal black with red.
static func palette(faction: String) -> Dictionary:
	if faction == "veil":
		return {
			"body": Color(0.2, 0.2, 0.22), "panel": Color(0.32, 0.31, 0.32),
			"dark": Color(0.07, 0.07, 0.08), "metal": Color(0.34, 0.34, 0.36),
			"concrete": Color(0.3, 0.29, 0.29), "hazard": Color(0.62, 0.07, 0.05),
		}
	return {
		"body": Color(0.56, 0.56, 0.5), "panel": Color(0.42, 0.44, 0.4),
		"dark": Color(0.15, 0.15, 0.14), "metal": Color(0.45, 0.46, 0.48),
		"concrete": Color(0.46, 0.45, 0.41), "hazard": Color(0.85, 0.66, 0.2),
	}


static func slot_material(slot: String, pal: Dictionary, team_color: Color) -> Material:
	match slot:
		"team":
			return mat(team_color.darkened(0.15), 0.0, 0.5, 0.3)
		"glow":
			return mat(team_color, 0.9, 0.5, 0.0, false)
		"glass":
			return mat(Color(0.1, 0.16, 0.2), 0.25, 0.1, 0.6, false)
		"lamp":
			return mat(Color(1.0, 0.85, 0.55), 1.8, 0.5, 0.0, false)
		"red":
			return mat(Color(0.9, 0.08, 0.04), 1.4, 0.5, 0.0, false)
		"tib":
			return mat(Color(0.2, 0.9, 0.3), 1.0, 0.3, 0.0, false)
		"metal":
			return mat(pal["metal"], 0.0, 0.35, 0.75)
		"dark":
			return mat(pal["dark"], 0.0, 0.8, 0.3)
		"hazard":
			return mat(pal["hazard"], 0.0, 0.45, 0.5)
		_:
			return mat(pal.get(slot, pal["body"]), 0.0, 0.7, 0.2)


static func build(model: String, team_color: Color, faction: String) -> Node3D:
	var data := _load_model(model, faction)
	if data.is_empty():
		push_warning("Missing model: %s" % model)
		return _fallback(team_color)
	var pal := palette(faction)
	var root := Node3D.new()
	var nodes := {}
	for p in data["parts"]:
		var parent: Node3D = root if p["parent"] == null else nodes[p["parent"]]
		var node: Node3D
		if p["parent"] == null:
			node = root
		else:
			node = Node3D.new()
			node.name = p["name"]
			node.position = p["pivot"]
			parent.add_child(node)
		nodes[p["name"]] = node
		if p["mesh"] != null:
			var mi := MeshInstance3D.new()
			mi.mesh = p["mesh"]
			var slots: Array = p["slots"]
			for i in slots.size():
				mi.set_surface_override_material(i, slot_material(slots[i], pal, team_color))
			node.add_child(mi)
	var meta: Dictionary = data["meta"]
	for key in ["turret", "cutter", "bin"]:
		if meta.has(key):
			root.set_meta(key, nodes[meta[key]])
	if meta.has("legs"):
		var legs: Array = []
		for l in meta["legs"]:
			legs.append(nodes[l])
		root.set_meta("walker", true)
		root.set_meta("legs", legs)
		root.set_meta("leg_swing", float(meta.get("leg_swing", 0.4)))
	if meta.has("muzzle_height"):
		root.set_meta("muzzle_height", float(meta["muzzle_height"]))
	return root


## The static mesh of a single-part model (terrain props drawn with MultiMesh).
static func mesh(model: String) -> Mesh:
	var data := _load_model(model, "")
	if data.is_empty():
		return BoxMesh.new()
	return data["parts"][0]["mesh"]


## Parses an .amdl file once; returns {"parts": [{name, parent, pivot, mesh, slots}], "meta"}.
static func _load_model(model: String, faction: String) -> Dictionary:
	var path := MODEL_DIR + "%s_%s.amdl" % [model, faction]
	if not FileAccess.file_exists(path):
		path = MODEL_DIR + "%s.amdl" % model
	if _models.has(path):
		return _models[path]
	var out := {}
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		_models[path] = out
		return out
	if f.get_buffer(4).get_string_from_ascii() != "AMDL":
		push_error("Not an AMDL file: %s" % path)
		_models[path] = out
		return out
	f.get_32()  # version
	var head: Dictionary = JSON.parse_string(f.get_buffer(f.get_32()).get_string_from_utf8())
	var raw_size := f.get_32()
	var raw := f.get_buffer(f.get_length() - f.get_position()).decompress(raw_size, FileAccess.COMPRESSION_DEFLATE)
	var parts: Array = []
	for p in head["parts"]:
		var mesh: ArrayMesh = null
		var slots: Array = []
		for s in p["surfaces"]:
			var n := int(s["count"])
			var o := int(s["offset"])
			var arrays := []
			arrays.resize(Mesh.ARRAY_MAX)
			arrays[Mesh.ARRAY_VERTEX] = raw.slice(o, o + n * 12).to_vector3_array()
			arrays[Mesh.ARRAY_NORMAL] = raw.slice(o + n * 12, o + n * 24).to_vector3_array()
			arrays[Mesh.ARRAY_COLOR] = raw.slice(o + n * 24, o + n * 40).to_color_array()
			if mesh == null:
				mesh = ArrayMesh.new()
			mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
			slots.append(s["slot"])
		var pv: Array = p["pivot"]
		parts.append({
			"name": p["name"], "parent": p["parent"], "mesh": mesh, "slots": slots,
			"pivot": Vector3(pv[0], pv[1], pv[2]),
		})
	out = {"parts": parts, "meta": head["meta"]}
	_models[path] = out
	return out


static func _fallback(team_color: Color) -> Node3D:
	var root := Node3D.new()
	var mi := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = Vector3(0.5, 0.5, 0.5)
	mi.mesh = bm
	mi.position.y = 0.25
	mi.material_override = mat(team_color, 0.0, 0.65, 0.25, false)
	root.add_child(mi)
	return root


## A translucent placement ghost of a footprint.
static func ghost(size: Vector2i) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = Vector3(size.x - 0.05, 0.6, size.y - 0.05)
	mi.mesh = bm
	var m := StandardMaterial3D.new()
	m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	m.albedo_color = Color(0.2, 1.0, 0.3, 0.35)
	mi.material_override = m
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	return mi
